# Polaris Gateway 配置文件
server:
  host: "127.0.0.1" # 默认只允许本地访问
  port: 28080        # 修改此处更换端口号
  read_timeout: 15
  write_timeout: 15

database:
  primary: "polaris.db"
  l2: "polaris_l2.db"

storage:
  vfs_path: "./data/vfs"